name: loumina_pi
services:
  server:
    build:
      context: ../../
      dockerfile: apps/server/Dockerfile
    image: loumina/server:dev
    container_name: loumina_server
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "${LOUMINA_PORT:-18080}:8080"
    restart: unless-stopped
